name: python

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
    
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: 3.8
          # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
          cache: pipenv
          
      - name: restore or create a python virtualenv
        uses: syphar/restore-virtualenv@v1
        with:
          # requirements-files to use for building the cache key
          requirement_files: |
            requirements.txt
            constraints.txt
            
